### ISSUE TITLE
Questions regarding the decoder and the dropped scores using hcqt

### ISSUE THREAD

**Issue by cloudscapes** [bmcfee/crema#33]
Hi Brian, 

I have two questions:
1)  you mentioned here https://github.com/bmcfee/crema/commit/79ed6d21f9c9aca73c7a5504f39aca767b75633a that by going to hcqt the scores dropped a bit ? do you know the reason for that?

2)  in crema/training/chords/ you mentioned that for training the decoder you switched back to the cqt before evaluation! this confuses me a bit! why did you switch back to cqt and not used the hcqt ??

**Comment by bmcfee** [comment]
First: sorry for the lag in responding to this!

To your questions: it's been a while since I was hacking on this project, but my recollection is that adding HCQT didn't provide any measurable improvement in accuracy, so we reverted the change because it's slightly more expensive to compute.

As for *why* HCQT didn't improve here, I'm not 100% certain.  One way to think of it is that the main thing that HCQT gets you is an easy way to resolve octave errors, but these don't matter for chords because all of our data is octave-folded.  If at some point in the future, we had sufficient data to properly model above-octave extensions (9ths, 11ths, 13ths, etc), then it might be worth trying again.

The other ingredient here is that the crema model does have access to the full spectrum for each frame, ie it's not fully convolutional in time and frequency (unlike the deep salience model).  Remember that HCQT doesn't add information, it just makes patterns easier to detect by localized time-frequency filters.  But since crema isn't using that kind of filter anyway, there may not be any benefit here.

I hope that helps!
